export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as User } from "./User";
export { default as DownloadedImages } from "./DownloadedImages";
export { default as LikedImages } from "./LikedImages";
export { default as ImageInfo } from "./ImageInfo";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
